apiVersion: v2
name: energy-app
description: Deployment for the energy monitoring pipeline
type: application
version: 0.1.0
appVersion: "1.0"


dependencies:
  - name: redis
    version: "17.3.17"
    repository: "https://charts.bitnami.com/bitnami"