apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    assignment-id: {{ .Values.global.assignmentId | quote }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # תוכלי לגשת לאתר דרך פורט זה ב-localhost
  selector:
    app: frontend